name: build

on:
  push:
    tags:
      - 'v*.*.*'
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      
      - name: Prepare
        run: |
          mkdir .debpkg
          mkdir -p .debpkg/usr/local/bin
          git clone https://github.com/cagriefegunay/deb-package-example.git
          cd deb-package-example && go build -v ./... && cp main ~/.debpkg/usr/local/bin

      - uses: jiro4989/build-deb-action@v2
        with:
          package: hello
          package_root: .debpkg
          maintainer: Example Boy <boy@example.com>
          version: ${{ github.ref }} # refs/tags/v*.*.*
          arch: 'amd64'
          desc: 'this is sample package.'
