name: build

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      
      - name: Build binaries
        run: go build -v ./...
      
      - name: Prepare
        run: |
          mkdir hello-deb
          mkdir -p hello-deb/usr/local/bin
          cp hello hello-deb/usr/local/bin
          
      - uses: jiro4989/build-deb-action@v2
        with:
          package: hello
          package_root: hello-deb
          maintainer: Example Boy <boy@example.com>
          version: ${{ github.ref }} # refs/tags/v*.*.*
          arch: 'amd64'
          desc: 'this is sample package.'

      - name: Checksum
        run: |
          sha256sum hello_*.deb

      - name: Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          files: hello_*.deb